jucha_ERP/urls.py
from django.contrib import admin
from django.urls import path, include
from reception import views
urlpatterns = [
    path('', views.dashboard),
    path('admin/', admin.site.urls),
    path('reception/', include('reception.urls')),
]

reception/urls.py
from django.urls import path

from . import views

app_name = 'reception'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('set-schedule/', views.set_schedule, name='set_schedule'),
    path('check-in/', views.check_in, name='check_in'),
    path('ongoing/', views.ongoing, name='ongoing'),
    path('serves/<int:serves_id>/', views.serves_detail, name='serves_detail'),
    path('serves/<int:serves_id>/change/', views.serves_change, name='change_status'),
    path('serves/<int:serves_id>/add-item/', views.add_item, name='add_item'),
    path('serves/<int:serves_id>/check-out/', views.check_out, name='check_out'),
    path('pay/<int:bill_id>/', views.pay, name='pay'),
    path('add-payment/<int:bill_id>/', views.add_payment, name='add_payment'),
    path('deposit-payment/<int:bill_id>/', views.use_deposit, name='use_deposit'),
    path('use-voucher/<int:bill_id>/', views.use_voucher, name='use_voucher'),
    path('use-meituan/<int:bill_id>/', views.use_meituan, name='use_meituan'),
    path('done/<int:bill_id>/', views.done, name='done'),
    path('create-card/<int:customer_id>/', views.create_card, name='create_card'),
    path('customer/', views.customer_detail, name='customer_detail'),
    path('credit-redeem/<int:customer_id>/', views.credit_redeem, name='credit_redeem'),
    path('manage/set-schedule', views.set_schedule, name='set_schedule'),
]

reception/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.urls import reverse
from decimal import Decimal

from .form import *
from .utils import *

# Create your views here.


def dashboard(request):
    context = {
        'serves_list': Serves.objects.filter(active=True),
        'available_maids': available_maids(),
        'available_places': Place.objects.filter(available=True),
        'user': request.user,
    }
    return render(request, 'reception/dashboard.html', context)


@login_required
@permission_required('reception.check_in_serves')
def check_in(request):
    if request.method == 'POST':
        form = CheckInForm(data=request.POST)
        if form.is_valid():
            start_serves(form.cleaned_data)
            return HttpResponseRedirect(reverse('reception:dashboard'))
    form = CheckInForm()
    return render(request, 'reception/check-in.html', {'form': form})


@login_required
def ongoing(request):
    context = {
        'serves_list': Serves.objects.filter(active=True),
        'ongoing_serves_charge': ServesCharge.objects.filter(paid=False),
        'ongoing_deposit_charge': DepositCharge.objects.filter(paid=False),
    }
    return render(request, 'reception/ongoing.html', context)


@login_required
def serves_detail(request, serves_id):
    if request.method == 'POST':
        return HttpResponseRedirect(reverse('serves_detail', args=[serves_id]))
    context = expense_detail(serves_id)
    context['serves'] = Serves.objects.get(pk=serves_id)
    return render(request, 'reception/serves-detail.html', context)


@login_required
@permission_required('reception.change_serves_status')
def serves_change(request, serves_id):
    if request.method == 'POST':
        sc = ServesChange(serves_id=serves_id, data=request.POST)
        if sc.is_valid():
            data = sc.cleaned_data
            if data['time'] is None:
                data['time'] = timezone.now()
            data['serves_id'] = serves_id
            success = change_status(data)
            print(success)
            return HttpResponseRedirect(reverse('reception:serves_detail', args=[serves_id]))
        else:
            return redirect(dashboard)
    form = ServesChange(serves_id=serves_id)
    context = {
        'serves_id': serves_id,
        'form': form,
    }
    return render(request, 'reception/serves-change.html', context)


@login_required
@permission_required('reception.change_serves_status')
def add_item(request, serves_id):
    if request.method == 'POST':
        af = AddItemForm(request.POST)
        if af.is_valid():
            serves_item = af.save(commit=False)
            serves_item.price = serves_item.item.price
            serves_item.serves_id = serves_id
            serves_item.save()
            return HttpResponseRedirect(reverse('reception:serves_detail', args=[serves_id]))
    form = AddItemForm()
    context = {
        'serves_id': serves_id,
        'form': form,
    }
    return render(request, 'reception/add-item.html', context)


@login_required
@permission_required('reception.check_out_serves')
def check_out(request, serves_id):
    if request.method == 'POST':
        mf = ManualForm(request.POST)
        if not mf.is_valid():
            return HttpResponseRedirect(reverse('reception:check_out', serves_id))
        serves = Serves.objects.get(pk=serves_id)

        context = expense_detail(serves_id)
        bill = Bill()
        if mf.cleaned_data['customer']:
            try:
                bill.customer = Customer.objects.get(phone=mf.cleaned_data['customer'])
            except ObjectDoesNotExist:
                customer = Customer(phone=mf.cleaned_data['customer'])
                customer.save()
                new_customer(customer)
                bill.customer = customer
        bill.save()
        charge = mf.save(commit=False)
        charge.total = context['total']
        charge.bill = bill
        charge.serves = serves
        charge.save()
        serves.end_serves()
        return HttpResponseRedirect(reverse('reception:pay', args=[bill.id]))

    context = expense_detail(serves_id, update=False)
    form = ManualForm
    context['form'] = form
    context['serves_id'] = serves_id
    return render(request, 'reception/check-out.html', context)


@login_required
@permission_required('reception.receive_money')
def pay(request, bill_id):
    bill = Bill.objects.get(pk=bill_id)
    logged_in = False
    have_voucher = False
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if not form.is_valid():
            try:
                customer = Customer.objects.get(phone=form.data['phone'])
            except ObjectDoesNotExist:
                return failure(request, bill_id, '手机号不正确')
        else:
            customer = form.save()
            new_customer(customer)
        bill.customer = customer
        bill.save()
    if bill.customer:
        logged_in = True
        if bill.customer.voucher_set.filter(used=False):
            have_voucher = True
    manual = 0
    if hasattr(bill, 'servescharge'):
        is_serves = True
        charge = bill.servescharge
        unpaid = charge.unpaid_amount()
        manual = charge.manual
        back_id = charge.serves.id
    elif hasattr(bill, 'depositcharge'):
        is_serves = False
        charge = bill.depositcharge
        unpaid = charge.unpaid_amount()
        back_id = bill.customer_id
    else:
        raise Exception
    incomes = bill.income_set.all()
    paid = charge.total + manual - unpaid
    cleared = unpaid <= 0
    context = {
        'is_serves': is_serves,
        'back_id': back_id,
        'bill': bill,
        'paid': paid,
        'total': charge.total + manual,
        'unpaid': max(0, unpaid),
        'cleared': cleared,
        'incomes': incomes,
        'form': form,
        'logged_in': logged_in,
        'have_voucher': have_voucher,
    }
    return render(request, 'reception/pay.html', context)


@login_required
@permission_required('reception.receive_money')
def add_payment(request, bill_id):
    if request.method == 'POST':
        pf = PaymentForm(request.POST)
        if not pf.is_valid():
            return failure(request, bill_id, '未知失败')
        income = pf.save(commit=False)
        income.bill_id = bill_id
        income.receiver = request.user
        income.save()
        return HttpResponseRedirect(reverse('reception:pay', args=[bill_id]))
    bill = Bill.objects.get(pk=bill_id)
    form = PaymentForm(unpaid=request.GET.get('unpaid'))
    context = {
        'bill': bill,
        'form': form,
    }
    return render(request, 'reception/add-payment.html', context)


@login_required
@permission_required('reception.receive_money')
def use_voucher(request, bill_id):
    bill = Bill.objects.get(pk=bill_id)
    if request.method == 'POST':
        form = UseVoucherForm(data=request.POST, customer=bill.customer_id)
        if form.is_valid():
            v = form.cleaned_data['voucher']
            bill.voucher = v
            bill.save()
        return HttpResponseRedirect(reverse('reception:pay', args=[bill_id]))
    form = UseVoucherForm(customer=bill.customer_id)
    return render(request, 'reception/use-voucher.html', {'form': form, 'bill': bill})


@login_required
def use_meituan(request, bill_id):
    bill = Bill.objects.get(pk=bill_id)
    if request.method == 'POST':
        form = UseMeituanForm(request.POST)
        if form.is_valid():
            v = form.save(commit=False)
        else:
            try:
                v = Voucher.objects.get(swift_number=request.POST['swift_number'])
                if v.used:
                    return failure(request, bill_id, '已使用过')
            except ObjectDoesNotExist:
                return failure(request, bill_id, '未知错误')
        if bill.customer:
            v.customer = bill.customer
        v.save()
        bill.voucher = v
        bill.save()
        return HttpResponseRedirect(reverse('reception:pay', args=[bill_id]))
    form = UseMeituanForm()
    return render(request, 'reception/use-voucher.html', {'form': form, 'bill': bill})


@login_required
@permission_required('reception.receive_money')
def use_deposit(request, bill_id):
    bill = Bill.objects.get(pk=bill_id)
    if request.method == 'POST':
        dp = DepositPaymentForm(data=request.POST, bill_id=bill_id)
        if not dp.is_valid():
            return failure(request, bill_id, '请输入正确数额')
        if dp.cleaned_data['amount'] > bill.customer.card.deposit:
            return failure(request, bill_id, '余额不足')

        deposit_payment = dp.save(commit=False)
        deposit_payment.bill = bill
        card = bill.customer.card
        deposit_payment.card = card
        card.deposit = card.deposit - dp.cleaned_data['amount']
        card.save()
        deposit_payment.save()
        bill.save()
        return HttpResponseRedirect(reverse('reception:pay', args=[bill_id]))
    form = DepositPaymentForm(bill_id=bill_id)
    context = {
        'bill': bill,
        'deposit': True,
        'form': form,
    }
    return render(request, 'reception/add-payment.html', context)


def done(request, bill_id):
    bill = Bill.objects.get(pk=bill_id)
    if bill.voucher:
        v = bill.voucher
        v.used = True
        v.save()
    if hasattr(bill, 'servescharge'):
        print('sc')
        charge = bill.servescharge
        charge.paid = True
        charge.save()
    else:
        print('dc')
        charge = bill.depositcharge
        charge.paid = True
        charge.save()
        if hasattr(bill.customer, 'card'):
            card = bill.customer.card
            card.deposit += charge.deposit_amount
        else:
            card = Card(deposit=charge.deposit_amount, customer=bill.customer)
        card.save()

templates/reception/add-payment.html
{% extends 'base.html' %}
{% block header %}
    <title>添加付款方式</title>
{% endblock %}
{% block content %}
    <form class="pure-form" action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="pure-button" value="确认入账">
        <button type="button" id="back" class="pure-button">返回</button>
    </form>
    <br>
    <script>
        $('#back').on('click',function(){
        window.location.href="{% url 'reception:pay' bill.id %}";
        })
    </script>
{% endblock %}

templates/reception/check-out.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Check Out</title>
</head>
<body>
{% if maid_detail %}
    <h2>女仆收费</h2>
    <table>
        <thead>
            <th>女仆</th>
            <th>时长/h</th>
            <th>单价</th>
            <th>总价</th>
        </thead>
        <tbody>
        {% for d in maid_detail %}
            <tr>
                <td>{{ d.name }}</td>
                <td>{{ d.hour }}</td>
                <td>{{ d.price }}</td>
                <td>{{ d.total }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}
{% if place_detail %}
    <h2>场地收费</h2>
    <table>
        <thead>
            <th>场地</th>
            <th>时长/h</th>
            <th>单价</th>
            <th>总价</th>
        </thead>
        <tbody>
        {% for d in place_detail %}
            <tr>
                <td>{{ d.name }}</td>
                <td>{{ d.hour }}</td>
                <td>{{ d.price }}</td>
                <td>{{ d.total }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}
{% if item_detail %}
    <h2>项目收费</h2>
    <table>
        <thead>
            <th>项目</th>
            <th>数量</th>
            <th>单价</th>
            <th>总价</th>
        </thead>
        <tbody>
        {% for d in item_detail %}
            <tr>
                <td>{{ d.name }}</td>
                <td>{{ d.hour }}</td>
                <td>{{ d.price }}</td>
                <td>{{ d.total }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}
<h2>总价：{{ total }}</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="付款">
</form>
<button type="button">
    <a href="{% url 'reception:serves_detail' serves_id %}">返回</a>
</button>
</body>
</html>

templates/reception/customer-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>客户信息</title>
</head>
<body>
{% if customer %}
    <p>手机号：{{ customer.phone }}</p>
    <p>积分：{{ customer.credit }}</p>
    {% if customer.card %}
        <p>储值卡余额：{{ customer.card.deposit }}</p>
        {% if customer.card.privilege.all %}
        <p>特权</p>
        <ul>
        {% for p in customer.card.privilege.all %}
            <li>{{ p }}</li>
        {% endfor %}
        </ul>
        {% endif %}
    {% endif %}
    <h3>进行中</h3>
    {% if ongoing_serves %}
        <h4>服务</h4>
        {% for s in ongoing_serves %}
        <a href="{% url 'reception:serves_detail' s.id %}"></a>
        {% endfor %}
    {% endif %}
    {% if ongoing_serves_charge %}
        <h4>未完成付款</h4>
        {% for s in ongoing_serves_charge %}
        <a href="{% url 'reception:pay' s.bill_id %}">{{ s }}</a>
        {% endfor %}
    {% endif %}
    {% if ongoing_deposit_charge %}
        <h4>未完成付款</h4>
        {% for s in ongoing_deposit_charge %}
        <a href="{% url 'reception:pay' s.bill_id %}">{{ s }}</a>
        {% endfor %}
    {% endif %}
    <h3>历史记录</h3>
    {% if past_serves %}
        <h4>服务记录</h4>
        {% for s in past_serves %}
        <a href="{% url 'reception:serves_detail' s.id %}">{{ s }}</a>
        {% endfor %}
    {% endif %}
    {% if past_serves_charge %}
        <h4>付款记录</h4>
        {% for s in past_serves_charge %}
        <p>{{ s }}</p>
        {% endfor %}
    {% endif %}
    {% if past_deposit_charge %}
        <h4>充值记录</h4>
        {% for s in past_deposit_charge %}
        <p>{{ s }}</p>
        {% endfor %}
    {% endif %}
{% else %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="确认">
    </form>
{% endif %}
    <button type="button">
        <a href="{% url 'reception:dashboard' %}">返回</a>
    </button>
    <button type="button">
        <a href="{% url 'reception:credit_redeem'  customer.id%}">积分兑换</a>
    </button>
</body>
</html>

templates/reception/done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>完成</title>
</head>
<body>
<p>支付完成！还有<span id="sp">3</span>秒跳转</p>
<script>
    onload=function () {
        setInterval(go,1000)
    };
    var x=2;
    function go() {

        if (x>=0){
            document.getElementById("sp").innerText=x;
        }else {
            location.href="{% if bill.servescharge %}{% url 'reception:dashboard' %}{% else %}{% url 'reception:customer_detail'%}?cid={{ bill.customer_id }}{% endif %}";
        }
        x--;
    }
</script>
</body>
</html>

templates/reception/failure.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>支付失败</title>
</head>
<body>
    <p>{{ message }}</p>
    <button type="button">
        <a href="{% url 'reception:pay' bill_id %}">返回</a>
    </button>
</body>
</html>

templates/reception/login.html
{% extends 'base.html' %}
{% block header %}
    <title>登陆</title>
{% endblock %}
{% block content %}
    <form class="pure-form" action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="pure-button" type="submit" value="登陆">
    </form>
{% endblock %}

templates/reception/ongoing.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>进行中</title>
</head>
<body>
{% if serves_list %}
    <ul>
    {% for serves in serves_list %}
        <li><a href="{% url 'reception:serves_detail' serves.id %}">{{ serves }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>没有正在进行的服务</p>
{% endif %}
{% if ongoing_serves_charge %}
    <ul>
    {% for charge in ongoing_serves_charge %}
        <li><a href="{% url 'reception:pay' charge.bill_id %}">{{ charge }}</a></li>
    {% endfor %}
    </ul>
{% endif %}
{% if ongoing_deposit_charge%}
    <ul>
    {% for charge in ongoing_deposit_charge %}
        <li><a href="{% url 'reception:serves_detail' charge.bill_id %}">{{ charge }}</a></li>
    {% endfor %}
    </ul>
{% endif %}
<button type="button">
    <a href="{% url 'reception:dashboard' %}">返回主页</a>
</button>
</body>
</html>

templates/reception/pay.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>付款</title>
</head>
<body>
    {% if logged_in %}
    <p>客户手机：{{ bill.customer.phone }}</p>
    {% else %}
    <form action="" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="确认">
    </form>
    {% endif %}
    <h2>总额:{{ total }}</h2>
    <h2>入账</h2>
    <table>
        <thead>
            <th>支付方式</th>
            <th>金额</th>
        </thead>
        <tbody>
        {% if incomes %}
            {% for i in incomes %}
            <tr>
                <td>{{ i.get_method_display }}</td>
                <td>{{ i.amount }}</td>
            </tr>
            {% endfor %}
        {% endif %}
        {% if bill.voucher %}
            <tr>
                <td>代金券{{ bill.voucher.type.name }}</td>
                <td>{{ bill.voucher.type.amount }}</td>
            </tr>
        {% endif %}
        {% if bill.depositpayment %}
            <tr>
                <td>会员卡支付</td>
                <td>{{ bill.depositpayment.amount }}</td>
            </tr>
        {% endif %}
            <tr>
                <td>合计入账</td>
                <td>{{ paid }}</td>
            </tr>
            <tr>
                <td>需支付</td>
                <td>{{ unpaid }}</td>
            </tr>
        </tbody>
    </table>
    {% if is_serves %}
        <button type="button">
            <a href="{% url 'reception:serves_detail' back_id %}">返回</a>
        </button>
            {% if bill.customer.card %}
            <button type="button">
                <a href="{% url 'reception:use_deposit' bill.id %}">会员卡付款</a>
            </button>
            {% elif bill.customer %}
            <button type="button">
                <a href="{% url 'reception:create_card' bill.customer.id %}">开卡</a>
            </button>
            {% endif %}
            {% if have_voucher %}
            <button type="button">
                <a href="{% url 'reception:use_voucher' bill.id %}">使用已有优惠券</a>
            </button>
            {% endif %}
        <button type="button">
            <a href="{% url 'reception:use_meituan' bill.id %}">使用美团优惠券</a>
        </button>
    {% else %}
        <button type="button">
        <a href="{% url 'reception:customer_detail'%}?cid={{ back_id }}">返回</a>
        </button>
    {% endif %}
    {% if cleared %}
    <a href="{% url 'reception:done' bill.id%}">完成</a>
    {% else %}
    <button type="button">
    <a href="{% url 'reception:add_payment' bill.id %}?unpaid={{ unpaid }}">添加入账</a>
    </button>
    {% endif %}
</body>
</html>

templates/reception/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>

</body>
</html>

templates/reception/serves-change.html
{% extends 'base.html' %}
{% block header %}
    <title>状态变更</title>
{% endblock %}
{% block content %}
    <form class="pure-form" action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input class="pure-button" type="submit" value="确认">
        <input type="reset" class="pure-button" value="重置">
        <button type="button" id="back" class="pure-button">返回</button>
    </form>

    <script>
        $('#back').on('click',function(){
        window.location.href="{% url 'reception:serves_detail' serves_id %}";
        })
    </script>
{% endblock %}

templates/reception/serves-detail.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>服务详情</title>
</head>
<body>
<p>女仆详情</p>
{% if maid_detail %}
    <table>
        <thead>
            <th>女仆</th>
            <th>开始</th>
            <th>结束</th>
            <th>时长/h</th>
            <th>单价</th>
            <th>总价</th>
        </thead>
        <tbody>
        {% for d in maid_detail %}
            <tr>
                <td>{{ d.name }}</td>
                <td>{{ d.start }}</td>
                {% if d.active %}
                    <td>----</td>
                {% else %}
                    <td>{{ d.end }}</td>
                {% endif %}                <td>{{ d.hour }}</td>
                <td>{{ d.price }}</td>
                <td>{{ d.total }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}
{% if place_detail %}
    <table>
        <thead>
            <th>场地</th>
            <th>开始</th>
            <th>结束</th>
            <th>时长/h</th>
            <th>单价</th>
            <th>总价</th>
        </thead>
        <tbody>
        {% for d in place_detail %}
            <tr>
                <td>{{ d.name }}</td>
                <td>{{ d.start }}</td>
                {% if d.active %}
                    <td>----</td>
                {% else %}
                    <td>{{ d.end }}</td>
                {% endif %}
                <td>{{ d.hour }}</td>
                <td>{{ d.price }}</td>
                <td>{{ d.total }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}
{% if item_detail %}
    <table>
        <thead>
            <th>项目</th>
            <th>数量</th>
            <th>单价</th>
            <th>总价</th>
        </thead>
        <tbody>
        {% for d in item_detail %}
            <tr>
                <td>{{ d.name }}</td>
                <td>{{ d.quantity }}</td>
                <td>{{ d.price }}</td>
                <td>{{ d.total }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}
{% if serves.active %}
<button type="button">
    <a href="{% url 'reception:change_status' serves.id %}">改变女仆/场地状态</a>
</button>
<button type="button">
    <a href="{% url 'reception:add_item' serves.id %}">增加项目</a>
</button>
<button type="button">
    <a href="{% url 'reception:check_out' serves.id %}">check out</a>
</button>
{% elif serves.servescharge.bill.customer %}
<button type="button">
    <a href="{% url 'reception:customer_detail'%}?cid={{ serves.servescharge.bill.customer_id }}">返回</a>
</button>
{% endif %}
<button type="button">
    <a href="{% url 'reception:dashboard' %}">返回主页</a>
</button>
</body>
</html>

templates/reception/set-schedule 2.html
{% extends 'base.html' %}
{% block header %}
<title>排班</title>
{% endblock %}
{% block content %}
    <form class="pure-form" action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="pure-button" value="确认">
        <button type="button" id="back" class="pure-button">返回</button>
    </form>
    <br>
    <script>
        $('#back').on('click',function(){
        window.location.href="{% url 'reception:dashboard' %}";
        })
    </script>
{% endblock %}

templates/reception/set-schedule.html
{% extends 'base.html' %}
{% block header %}
<title>排班</title>
{% endblock %}
{% block content %}
    <form class="pure-form" action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="pure-button" value="确认">
        <button type="button" id="back" class="pure-button">返回</button>
    </form>
    <br>
    <script>
        $('#back').on('click',function(){
        window.location.href="{% url 'reception:dashboard' %}";
        })
    </script>
{% endblock %}

templates/reception/use-deposit.html
{% extends 'base.html' %}
{% block header %}
    <title>会员卡支付</title>
{% endblock %}
{% block content %}
    <p>余额：{{ deposit }}</p>
    <form class="pure-form" action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="pure-button" value="确认">
        <button type="button" id="back" class="pure-button">返回</button>
    </form>
    <br>
    <script>
        $('#back').on('click',function(){
        window.location.href="{% url 'reception:pay' bill.id %}";
        })
    </script>
{% endblock %}